// Emojis para el chat de WhatsApp del CRM, agrupados como en el celu (los más usados en ventas primero).
export const EMOJI_GROUPS: { name: string; icon: string; emojis: string[] }[] = [
  {
    name: "Caritas",
    icon: "😊",
    emojis: [
      ..."😀😃😄😁😆😅🤣😂🙂😉😊😇🥰😍🤩😘😗😚😙😋😛😜🤪😝🤑🤗🤭🤫🤔🤐🤨😐😑😶😏😒🙄😬😌😔😪🤤😴😷🤒🤕🤢🥵🥶🥴😵🤯🤠🥳😎🤓🧐😕😟🙁😮😯😲😳🥺😦😧😨😰😥😢😭😱😖😣😞😓😩😫🥱😤😡😠🤬😈💀💩🤡👻👽🤖",
    ],
  },
  {
    name: "Gestos",
    icon: "👍",
    emojis: [..."👍👎👌🤌🤏✌🤞🤟🤘🤙👈👉👆👇☝👋🤚🖐✋🖖👏🙌👐🤲🤝🙏✍💪🦾👀👁👄💋🫶"],
  },
  {
    name: "Corazones",
    icon: "❤️",
    emojis: [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "✨",
      "⭐",
      "🌟",
      "💫",
      "🔥",
      "💯",
      "💥",
      "💢",
      "💤",
    ],
  },
  {
    name: "Ropa y compras",
    icon: "🛍️",
    emojis: [..."👕👖🧥🥼🦺👔👗👘🩱🩳🧦🧤🧣🎩🧢👒🎓⛑👟👞🥾🥿👠👡👢🩴👜👛👝🎒🧳👓🕶💍💄"].concat([
      "🛍️",
      "🛒",
      "🏷️",
      "💳",
      "💵",
      "💰",
      "🧾",
      "📦",
      "🚚",
      "🛵",
      "🏬",
      "🏪",
      "📏",
      "✂️",
      "🪡",
      "🧵",
    ]),
  },
  {
    name: "Celebrar",
    icon: "🎉",
    emojis: [..."🎉🎊🎈🎁🎀🎂🍰🧁🥂🍾🍻🎄🎃🏆🥇🥈🥉🎯🎶🎵"].concat(["🎟️", "📣", "📢"]),
  },
  {
    name: "Cosas",
    icon: "📱",
    emojis: [..."📱💻📷📸📹🎥📞☎📲📩📨📧💬💭🗨📅📆🕐⏰⌛⏳📍🗺🏠🏢🚗🚕🚌✈🚀⚡☀🌧❄☔🌈🌙"].concat([
      "✅",
      "☑️",
      "✔️",
      "❌",
      "❗",
      "❓",
      "⚠️",
      "🆕",
      "🆓",
      "🔝",
      "🔜",
      "👉🏻",
      "➡️",
      "⬅️",
      "⬆️",
      "⬇️",
      "🔄",
    ]),
  },
  {
    name: "Comida",
    icon: "🍕",
    emojis: [..."☕🧉🍵🥤🍺🍷🍕🍔🍟🌭🥪🌮🍣🍝🥗🍦🍩🍪🍫🍬🍭🍿🥐🥯🍎🍌🍉🍓🍒🥑"],
  },
  {
    name: "Animales",
    icon: "🐶",
    emojis: [..."🐶🐱🐭🐹🐰🦊🐻🐼🐨🐯🦁🐮🐷🐸🐵🙈🙉🙊🐔🐧🐦🦄🐝🦋🐢🐍🐙🐬🐳🦈🐺"],
  },
];
